# Generated by Django 5.2.17 on 2026-08-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_nodes', models.IntegerField(default=0)),
                ('total_edges', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('graph_source', models.CharField(default='OSM', help_text='Source of the graph data', max_length=255)),
                ('graph_region', models.CharField(default='Kathmandu', help_text='Geographic region', max_length=255)),
                ('file_size_mb', models.FloatField(default=0, help_text='Size of graph file in MB')),
                ('graph_status', models.CharField(choices=[('active', 'Active'), ('loading', 'Loading'), ('error', 'Error')], default='active', max_length=50)),
                ('status_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Graph Metadata',
                'verbose_name_plural': 'Graph Metadata',
            },
        ),
        migrations.CreateModel(
            name='RouteStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('dijkstra', 'Dijkstra'), ('astar', 'A*')], max_length=20)),
                ('execution_time_ms', models.FloatField(help_text='Execution time in milliseconds')),
                ('distance_meters', models.FloatField(help_text='Route distance in meters')),
                ('nodes_explored', models.IntegerField(help_text='Number of nodes explored')),
                ('path_length', models.IntegerField(help_text='Number of nodes in the path')),
                ('start_lat', models.FloatField()),
                ('start_lon', models.FloatField()),
                ('end_lat', models.FloatField()),
                ('end_lon', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['algorithm', '-created_at'], name='routing_rou_algorit_f5dc7f_idx'), models.Index(fields=['-created_at'], name='routing_rou_created_691087_idx')],
            },
        ),
    ]
